name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main ]   # o "master" si usas master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Opcional: evita que GitHub trate tu sitio como Jekyll (útil si tienes carpetas que empiezan con "_")
      - name: Disable Jekyll
        run: echo > .nojekyll

      # Si tu sitio está en la raíz del repo, usa "."
      # Si está en una carpeta (ej. "dist" o "docs"), cambia path a esa carpeta
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ejemplo  # ./dist  ó  ./docs  si corresponde

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
